
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
example_test_data_ratio: 0.2
example_num_train_iter: 10000
example_learning_rate: 0.01


transformations:
  random_rotation: 20
  resize:
    height: 224
    width: 224

  normalize:
    #Color images have three channels (red, green, blue), therefore you need three parameters to normalize each channel.
    #The first tuple (0.5, 0.5, 0.5) is the mean for all three channels and the second (0.5, 0.5, 0.5)
    #is the standard deviation for all three channels.
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]


